[pytest]
markers =
    login: marks tests as login feature tests
    regression: marks tests as regression suite
    sanity: marks tests as sanity check tests
    test_marker_demo: marks tests as demo tests
    test_code: marks tests as test code
    testisnotrequired: marks tests as test code1
    testisnotrequired2: marks tests as test code2